// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/provider/provider.proto

package provider

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlanResponse_Action int32

const (
	PlanResponse_NOOP    PlanResponse_Action = 0
	PlanResponse_CREATE  PlanResponse_Action = 1
	PlanResponse_UPDATE  PlanResponse_Action = 2
	PlanResponse_DELETE  PlanResponse_Action = 3
	PlanResponse_REPLACE PlanResponse_Action = 4
)

// Enum value maps for PlanResponse_Action.
var (
	PlanResponse_Action_name = map[int32]string{
		0: "NOOP",
		1: "CREATE",
		2: "UPDATE",
		3: "DELETE",
		4: "REPLACE",
	}
	PlanResponse_Action_value = map[string]int32{
		"NOOP":    0,
		"CREATE":  1,
		"UPDATE":  2,
		"DELETE":  3,
		"REPLACE": 4,
	}
)

func (x PlanResponse_Action) Enum() *PlanResponse_Action {
	p := new(PlanResponse_Action)
	*p = x
	return p
}

func (x PlanResponse_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlanResponse_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_provider_provider_proto_enumTypes[0].Descriptor()
}

func (PlanResponse_Action) Type() protoreflect.EnumType {
	return &file_proto_provider_provider_proto_enumTypes[0]
}

func (x PlanResponse_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlanResponse_Action.Descriptor instead.
func (PlanResponse_Action) EnumDescriptor() ([]byte, []int) {
	return file_proto_provider_provider_proto_rawDescGZIP(), []int{5, 0}
}

type Diagnostic_Severity int32

const (
	Diagnostic_ERROR   Diagnostic_Severity = 0
	Diagnostic_WARNING Diagnostic_Severity = 1
)

// Enum value maps for Diagnostic_Severity.
var (
	Diagnostic_Severity_name = map[int32]string{
		0: "ERROR",
		1: "WARNING",
	}
	Diagnostic_Severity_value = map[string]int32{
		"ERROR":   0,
		"WARNING": 1,
	}
)

func (x Diagnostic_Severity) Enum() *Diagnostic_Severity {
	p := new(Diagnostic_Severity)
	*p = x
	return p
}

func (x Diagnostic_Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Diagnostic_Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_provider_provider_proto_enumTypes[1].Descriptor()
}

func (Diagnostic_Severity) Type() protoreflect.EnumType {
	return &file_proto_provider_provider_proto_enumTypes[1]
}

func (x Diagnostic_Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Diagnostic_Severity.Descriptor instead.
func (Diagnostic_Severity) EnumDescriptor() ([]byte, []int) {
	return file_proto_provider_provider_proto_rawDescGZIP(), []int{12, 0}
}

type GetSchemaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSchemaRequest) Reset() {
	*x = GetSchemaRequest{}
	mi := &file_proto_provider_provider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchemaRequest) ProtoMessage() {}

func (x *GetSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_provider_provider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchemaRequest.ProtoReflect.Descriptor instead.
func (*GetSchemaRequest) Descriptor() ([]byte, []int) {
	return file_proto_provider_provider_proto_rawDescGZIP(), []int{0}
}

type GetSchemaResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Helper to return the PKL schema definition for the provider
	PklSchema     string `protobuf:"bytes,1,opt,name=pkl_schema,json=pklSchema,proto3" json:"pkl_schema,omitempty"`
	PklVersion    string `protobuf:"bytes,2,opt,name=pkl_version,json=pklVersion,proto3" json:"pkl_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSchemaResponse) Reset() {
	*x = GetSchemaResponse{}
	mi := &file_proto_provider_provider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchemaResponse) ProtoMessage() {}

func (x *GetSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_provider_provider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchemaResponse.ProtoReflect.Descriptor instead.
func (*GetSchemaResponse) Descriptor() ([]byte, []int) {
	return file_proto_provider_provider_proto_rawDescGZIP(), []int{1}
}

func (x *GetSchemaResponse) GetPklSchema() string {
	if x != nil {
		return x.PklSchema
	}
	return ""
}

func (x *GetSchemaResponse) GetPklVersion() string {
	if x != nil {
		return x.PklVersion
	}
	return ""
}

type ConfigureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigJson    []byte                 `protobuf:"bytes,1,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureRequest) Reset() {
	*x = ConfigureRequest{}
	mi := &file_proto_provider_provider_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureRequest) ProtoMessage() {}

func (x *ConfigureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_provider_provider_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureRequest.ProtoReflect.Descriptor instead.
func (*ConfigureRequest) Descriptor() ([]byte, []int) {
	return file_proto_provider_provider_proto_rawDescGZIP(), []int{2}
}

func (x *ConfigureRequest) GetConfigJson() []byte {
	if x != nil {
		return x.ConfigJson
	}
	return nil
}

type ConfigureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Diagnostics   []*Diagnostic          `protobuf:"bytes,1,rep,name=diagnostics,proto3" json:"diagnostics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureResponse) Reset() {
	*x = ConfigureResponse{}
	mi := &file_proto_provider_provider_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureResponse) ProtoMessage() {}

func (x *ConfigureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_provider_provider_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureResponse.ProtoReflect.Descriptor instead.
func (*ConfigureResponse) Descriptor() ([]byte, []int) {
	return file_proto_provider_provider_proto_rawDescGZIP(), []int{3}
}

func (x *ConfigureResponse) GetDiagnostics() []*Diagnostic {
	if x != nil {
		return x.Diagnostics
	}
	return nil
}

type PlanRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Type              string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DesiredConfigJson []byte                 `protobuf:"bytes,3,opt,name=desired_config_json,json=desiredConfigJson,proto3" json:"desired_config_json,omitempty"`
	PriorStateJson    []byte                 `protobuf:"bytes,4,opt,name=prior_state_json,json=priorStateJson,proto3" json:"prior_state_json,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PlanRequest) Reset() {
	*x = PlanRequest{}
	mi := &file_proto_provider_provider_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanRequest) ProtoMessage() {}

func (x *PlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_provider_provider_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanRequest.ProtoReflect.Descriptor instead.
func (*PlanRequest) Descriptor() ([]byte, []int) {
	return file_proto_provider_provider_proto_rawDescGZIP(), []int{4}
}

func (x *PlanRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PlanRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PlanRequest) GetDesiredConfigJson() []byte {
	if x != nil {
		return x.DesiredConfigJson
	}
	return nil
}

func (x *PlanRequest) GetPriorStateJson() []byte {
	if x != nil {
		return x.PriorStateJson
	}
	return nil
}

type PlanResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Action            PlanResponse_Action    `protobuf:"varint,1,opt,name=action,proto3,enum=picklr.provider.PlanResponse_Action" json:"action,omitempty"`
	ChangedAttributes []string               `protobuf:"bytes,2,rep,name=changed_attributes,json=changedAttributes,proto3" json:"changed_attributes,omitempty"`
	PlannedStateJson  []byte                 `protobuf:"bytes,3,opt,name=planned_state_json,json=plannedStateJson,proto3" json:"planned_state_json,omitempty"`
	Diagnostics       []*Diagnostic          `protobuf:"bytes,4,rep,name=diagnostics,proto3" json:"diagnostics,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PlanResponse) Reset() {
	*x = PlanResponse{}
	mi := &file_proto_provider_provider_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanResponse) ProtoMessage() {}

func (x *PlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_provider_provider_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanResponse.ProtoReflect.Descriptor instead.
func (*PlanResponse) Descriptor() ([]byte, []int) {
	return file_proto_provider_provider_proto_rawDescGZIP(), []int{5}
}

func (x *PlanResponse) GetAction() PlanResponse_Action {
	if x != nil {
		return x.Action
	}
	return PlanResponse_NOOP
}

func (x *PlanResponse) GetChangedAttributes() []string {
	if x != nil {
		return x.ChangedAttributes
	}
	return nil
}

func (x *PlanResponse) GetPlannedStateJson() []byte {
	if x != nil {
		return x.PlannedStateJson
	}
	return nil
}

func (x *PlanResponse) GetDiagnostics() []*Diagnostic {
	if x != nil {
		return x.Diagnostics
	}
	return nil
}

type ApplyRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Type              string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DesiredConfigJson []byte                 `protobuf:"bytes,3,opt,name=desired_config_json,json=desiredConfigJson,proto3" json:"desired_config_json,omitempty"`
	PriorStateJson    []byte                 `protobuf:"bytes,4,opt,name=prior_state_json,json=priorStateJson,proto3" json:"prior_state_json,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ApplyRequest) Reset() {
	*x = ApplyRequest{}
	mi := &file_proto_provider_provider_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyRequest) ProtoMessage() {}

func (x *ApplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_provider_provider_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyRequest.ProtoReflect.Descriptor instead.
func (*ApplyRequest) Descriptor() ([]byte, []int) {
	return file_proto_provider_provider_proto_rawDescGZIP(), []int{6}
}

func (x *ApplyRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ApplyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ApplyRequest) GetDesiredConfigJson() []byte {
	if x != nil {
		return x.DesiredConfigJson
	}
	return nil
}

func (x *ApplyRequest) GetPriorStateJson() []byte {
	if x != nil {
		return x.PriorStateJson
	}
	return nil
}

type ApplyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewStateJson  []byte                 `protobuf:"bytes,1,opt,name=new_state_json,json=newStateJson,proto3" json:"new_state_json,omitempty"`
	Diagnostics   []*Diagnostic          `protobuf:"bytes,2,rep,name=diagnostics,proto3" json:"diagnostics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyResponse) Reset() {
	*x = ApplyResponse{}
	mi := &file_proto_provider_provider_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyResponse) ProtoMessage() {}

func (x *ApplyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_provider_provider_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyResponse.ProtoReflect.Descriptor instead.
func (*ApplyResponse) Descriptor() ([]byte, []int) {
	return file_proto_provider_provider_proto_rawDescGZIP(), []int{7}
}

func (x *ApplyResponse) GetNewStateJson() []byte {
	if x != nil {
		return x.NewStateJson
	}
	return nil
}

func (x *ApplyResponse) GetDiagnostics() []*Diagnostic {
	if x != nil {
		return x.Diagnostics
	}
	return nil
}

type ReadRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Type             string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Id               string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	CurrentStateJson []byte                 `protobuf:"bytes,3,opt,name=current_state_json,json=currentStateJson,proto3" json:"current_state_json,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ReadRequest) Reset() {
	*x = ReadRequest{}
	mi := &file_proto_provider_provider_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRequest) ProtoMessage() {}

func (x *ReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_provider_provider_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRequest.ProtoReflect.Descriptor instead.
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return file_proto_provider_provider_proto_rawDescGZIP(), []int{8}
}

func (x *ReadRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ReadRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReadRequest) GetCurrentStateJson() []byte {
	if x != nil {
		return x.CurrentStateJson
	}
	return nil
}

type ReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewStateJson  []byte                 `protobuf:"bytes,1,opt,name=new_state_json,json=newStateJson,proto3" json:"new_state_json,omitempty"`
	Exists        bool                   `protobuf:"varint,2,opt,name=exists,proto3" json:"exists,omitempty"`
	Diagnostics   []*Diagnostic          `protobuf:"bytes,3,rep,name=diagnostics,proto3" json:"diagnostics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadResponse) Reset() {
	*x = ReadResponse{}
	mi := &file_proto_provider_provider_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResponse) ProtoMessage() {}

func (x *ReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_provider_provider_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResponse.ProtoReflect.Descriptor instead.
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return file_proto_provider_provider_proto_rawDescGZIP(), []int{9}
}

func (x *ReadResponse) GetNewStateJson() []byte {
	if x != nil {
		return x.NewStateJson
	}
	return nil
}

func (x *ReadResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *ReadResponse) GetDiagnostics() []*Diagnostic {
	if x != nil {
		return x.Diagnostics
	}
	return nil
}

type DeleteRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Type             string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Id               string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	CurrentStateJson []byte                 `protobuf:"bytes,3,opt,name=current_state_json,json=currentStateJson,proto3" json:"current_state_json,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_proto_provider_provider_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_provider_provider_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_proto_provider_provider_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteRequest) GetCurrentStateJson() []byte {
	if x != nil {
		return x.CurrentStateJson
	}
	return nil
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Diagnostics   []*Diagnostic          `protobuf:"bytes,1,rep,name=diagnostics,proto3" json:"diagnostics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_proto_provider_provider_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_provider_provider_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_proto_provider_provider_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteResponse) GetDiagnostics() []*Diagnostic {
	if x != nil {
		return x.Diagnostics
	}
	return nil
}

type Diagnostic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Severity      Diagnostic_Severity    `protobuf:"varint,1,opt,name=severity,proto3,enum=picklr.provider.Diagnostic_Severity" json:"severity,omitempty"`
	Summary       string                 `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	Detail        string                 `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Diagnostic) Reset() {
	*x = Diagnostic{}
	mi := &file_proto_provider_provider_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Diagnostic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Diagnostic) ProtoMessage() {}

func (x *Diagnostic) ProtoReflect() protoreflect.Message {
	mi := &file_proto_provider_provider_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Diagnostic.ProtoReflect.Descriptor instead.
func (*Diagnostic) Descriptor() ([]byte, []int) {
	return file_proto_provider_provider_proto_rawDescGZIP(), []int{12}
}

func (x *Diagnostic) GetSeverity() Diagnostic_Severity {
	if x != nil {
		return x.Severity
	}
	return Diagnostic_ERROR
}

func (x *Diagnostic) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Diagnostic) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

var File_proto_provider_provider_proto protoreflect.FileDescriptor

const file_proto_provider_provider_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/provider/provider.proto\x12\x0fpicklr.provider\"\x12\n" +
	"\x10GetSchemaRequest\"S\n" +
	"\x11GetSchemaResponse\x12\x1d\n" +
	"\n" +
	"pkl_schema\x18\x01 \x01(\tR\tpklSchema\x12\x1f\n" +
	"\vpkl_version\x18\x02 \x01(\tR\n" +
	"pklVersion\"3\n" +
	"\x10ConfigureRequest\x12\x1f\n" +
	"\vconfig_json\x18\x01 \x01(\fR\n" +
	"configJson\"R\n" +
	"\x11ConfigureResponse\x12=\n" +
	"\vdiagnostics\x18\x01 \x03(\v2\x1b.picklr.provider.DiagnosticR\vdiagnostics\"\x8f\x01\n" +
	"\vPlanRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12.\n" +
	"\x13desired_config_json\x18\x03 \x01(\fR\x11desiredConfigJson\x12(\n" +
	"\x10prior_state_json\x18\x04 \x01(\fR\x0epriorStateJson\"\xad\x02\n" +
	"\fPlanResponse\x12<\n" +
	"\x06action\x18\x01 \x01(\x0e2$.picklr.provider.PlanResponse.ActionR\x06action\x12-\n" +
	"\x12changed_attributes\x18\x02 \x03(\tR\x11changedAttributes\x12,\n" +
	"\x12planned_state_json\x18\x03 \x01(\fR\x10plannedStateJson\x12=\n" +
	"\vdiagnostics\x18\x04 \x03(\v2\x1b.picklr.provider.DiagnosticR\vdiagnostics\"C\n" +
	"\x06Action\x12\b\n" +
	"\x04NOOP\x10\x00\x12\n" +
	"\n" +
	"\x06CREATE\x10\x01\x12\n" +
	"\n" +
	"\x06UPDATE\x10\x02\x12\n" +
	"\n" +
	"\x06DELETE\x10\x03\x12\v\n" +
	"\aREPLACE\x10\x04\"\x90\x01\n" +
	"\fApplyRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12.\n" +
	"\x13desired_config_json\x18\x03 \x01(\fR\x11desiredConfigJson\x12(\n" +
	"\x10prior_state_json\x18\x04 \x01(\fR\x0epriorStateJson\"t\n" +
	"\rApplyResponse\x12$\n" +
	"\x0enew_state_json\x18\x01 \x01(\fR\fnewStateJson\x12=\n" +
	"\vdiagnostics\x18\x02 \x03(\v2\x1b.picklr.provider.DiagnosticR\vdiagnostics\"_\n" +
	"\vReadRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12,\n" +
	"\x12current_state_json\x18\x03 \x01(\fR\x10currentStateJson\"\x8b\x01\n" +
	"\fReadResponse\x12$\n" +
	"\x0enew_state_json\x18\x01 \x01(\fR\fnewStateJson\x12\x16\n" +
	"\x06exists\x18\x02 \x01(\bR\x06exists\x12=\n" +
	"\vdiagnostics\x18\x03 \x03(\v2\x1b.picklr.provider.DiagnosticR\vdiagnostics\"a\n" +
	"\rDeleteRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12,\n" +
	"\x12current_state_json\x18\x03 \x01(\fR\x10currentStateJson\"O\n" +
	"\x0eDeleteResponse\x12=\n" +
	"\vdiagnostics\x18\x01 \x03(\v2\x1b.picklr.provider.DiagnosticR\vdiagnostics\"\xa4\x01\n" +
	"\n" +
	"Diagnostic\x12@\n" +
	"\bseverity\x18\x01 \x01(\x0e2$.picklr.provider.Diagnostic.SeverityR\bseverity\x12\x18\n" +
	"\asummary\x18\x02 \x01(\tR\asummary\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detail\"\"\n" +
	"\bSeverity\x12\t\n" +
	"\x05ERROR\x10\x00\x12\v\n" +
	"\aWARNING\x10\x012\xcf\x03\n" +
	"\bProvider\x12R\n" +
	"\tGetSchema\x12!.picklr.provider.GetSchemaRequest\x1a\".picklr.provider.GetSchemaResponse\x12R\n" +
	"\tConfigure\x12!.picklr.provider.ConfigureRequest\x1a\".picklr.provider.ConfigureResponse\x12C\n" +
	"\x04Plan\x12\x1c.picklr.provider.PlanRequest\x1a\x1d.picklr.provider.PlanResponse\x12F\n" +
	"\x05Apply\x12\x1d.picklr.provider.ApplyRequest\x1a\x1e.picklr.provider.ApplyResponse\x12C\n" +
	"\x04Read\x12\x1c.picklr.provider.ReadRequest\x1a\x1d.picklr.provider.ReadResponse\x12I\n" +
	"\x06Delete\x12\x1e.picklr.provider.DeleteRequest\x1a\x1f.picklr.provider.DeleteResponseB0Z.github.com/picklr-io/picklr/pkg/proto/providerb\x06proto3"

var (
	file_proto_provider_provider_proto_rawDescOnce sync.Once
	file_proto_provider_provider_proto_rawDescData []byte
)

func file_proto_provider_provider_proto_rawDescGZIP() []byte {
	file_proto_provider_provider_proto_rawDescOnce.Do(func() {
		file_proto_provider_provider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_provider_provider_proto_rawDesc), len(file_proto_provider_provider_proto_rawDesc)))
	})
	return file_proto_provider_provider_proto_rawDescData
}

var file_proto_provider_provider_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_provider_provider_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_provider_provider_proto_goTypes = []any{
	(PlanResponse_Action)(0),  // 0: picklr.provider.PlanResponse.Action
	(Diagnostic_Severity)(0),  // 1: picklr.provider.Diagnostic.Severity
	(*GetSchemaRequest)(nil),  // 2: picklr.provider.GetSchemaRequest
	(*GetSchemaResponse)(nil), // 3: picklr.provider.GetSchemaResponse
	(*ConfigureRequest)(nil),  // 4: picklr.provider.ConfigureRequest
	(*ConfigureResponse)(nil), // 5: picklr.provider.ConfigureResponse
	(*PlanRequest)(nil),       // 6: picklr.provider.PlanRequest
	(*PlanResponse)(nil),      // 7: picklr.provider.PlanResponse
	(*ApplyRequest)(nil),      // 8: picklr.provider.ApplyRequest
	(*ApplyResponse)(nil),     // 9: picklr.provider.ApplyResponse
	(*ReadRequest)(nil),       // 10: picklr.provider.ReadRequest
	(*ReadResponse)(nil),      // 11: picklr.provider.ReadResponse
	(*DeleteRequest)(nil),     // 12: picklr.provider.DeleteRequest
	(*DeleteResponse)(nil),    // 13: picklr.provider.DeleteResponse
	(*Diagnostic)(nil),        // 14: picklr.provider.Diagnostic
}
var file_proto_provider_provider_proto_depIdxs = []int32{
	14, // 0: picklr.provider.ConfigureResponse.diagnostics:type_name -> picklr.provider.Diagnostic
	0,  // 1: picklr.provider.PlanResponse.action:type_name -> picklr.provider.PlanResponse.Action
	14, // 2: picklr.provider.PlanResponse.diagnostics:type_name -> picklr.provider.Diagnostic
	14, // 3: picklr.provider.ApplyResponse.diagnostics:type_name -> picklr.provider.Diagnostic
	14, // 4: picklr.provider.ReadResponse.diagnostics:type_name -> picklr.provider.Diagnostic
	14, // 5: picklr.provider.DeleteResponse.diagnostics:type_name -> picklr.provider.Diagnostic
	1,  // 6: picklr.provider.Diagnostic.severity:type_name -> picklr.provider.Diagnostic.Severity
	2,  // 7: picklr.provider.Provider.GetSchema:input_type -> picklr.provider.GetSchemaRequest
	4,  // 8: picklr.provider.Provider.Configure:input_type -> picklr.provider.ConfigureRequest
	6,  // 9: picklr.provider.Provider.Plan:input_type -> picklr.provider.PlanRequest
	8,  // 10: picklr.provider.Provider.Apply:input_type -> picklr.provider.ApplyRequest
	10, // 11: picklr.provider.Provider.Read:input_type -> picklr.provider.ReadRequest
	12, // 12: picklr.provider.Provider.Delete:input_type -> picklr.provider.DeleteRequest
	3,  // 13: picklr.provider.Provider.GetSchema:output_type -> picklr.provider.GetSchemaResponse
	5,  // 14: picklr.provider.Provider.Configure:output_type -> picklr.provider.ConfigureResponse
	7,  // 15: picklr.provider.Provider.Plan:output_type -> picklr.provider.PlanResponse
	9,  // 16: picklr.provider.Provider.Apply:output_type -> picklr.provider.ApplyResponse
	11, // 17: picklr.provider.Provider.Read:output_type -> picklr.provider.ReadResponse
	13, // 18: picklr.provider.Provider.Delete:output_type -> picklr.provider.DeleteResponse
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_provider_provider_proto_init() }
func file_proto_provider_provider_proto_init() {
	if File_proto_provider_provider_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_provider_provider_proto_rawDesc), len(file_proto_provider_provider_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_provider_provider_proto_goTypes,
		DependencyIndexes: file_proto_provider_provider_proto_depIdxs,
		EnumInfos:         file_proto_provider_provider_proto_enumTypes,
		MessageInfos:      file_proto_provider_provider_proto_msgTypes,
	}.Build()
	File_proto_provider_provider_proto = out.File
	file_proto_provider_provider_proto_goTypes = nil
	file_proto_provider_provider_proto_depIdxs = nil
}
